### ISSUE TITLE
Error when going back without saving on newly created item

### ISSUE THREAD

**Issue by Mihaiii** [Starcounter/Content#117]
### Steps to reproduce
1. Run Content app v.1.1.0
2. Run Sign In
3. Run Website
4. Navigate to `/content/cms`
5. Click "Create"
6. Click "Go back" 
### Expected result
Redirects to `/content/cms`
### Actual result
I get an error.

> System.ArgumentNullException: Value cannot be null.
> Parameter name: obj
>    at Starcounter.DbHelper.GetObjectID(Object obj) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9794\Level1\src\Starcounter\Mock\DbHelper.cs:line 92
>    at Content.ViewModels.CmsItemPage.Handle(CancelTrigger action) in C:\Users\Mihai\Desktop\New folder (9)\New folder\Content\src\Content\ViewModels\CmsItemPage.json.cs:line 79
>    at Content.ViewModels.CmsItemPage.JsonByExample.Schema.<>c.<.ctor>b__0_20(Json pup, Input`1 input)
>    at Starcounter.Templates.Property`1.InvokeHandler(Json parent, Input`1 input) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9794\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 267
>    at Starcounter.Templates.Property`1.ProcessInput(Json parent, T value) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9794\Level1\src\Starcounter.XSON\Templates\Foundation\Property.cs:line 289
>    at Starcounter.XSON.DefaultPatchHandler.ParseAndProcess(TLong property, Json parent, String valueStr) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9794\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 149
>    at Starcounter.Internal.TransactionManager.Scope(TransactionHandle handle, Action action) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9794\Level1\src\Starcounter\TransactionManager.cs:line 551
>    at Starcounter.Transaction.Scope(Action action) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9794\Level1\src\Starcounter\Transaction.cs:line 224
>    at Starcounter.Advanced.XSON.JsonExtension.Scope(Json json, Action action) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9794\Level1\src\Starcounter.XSON\Advanced\JsonExtension.cs:line 67
>    at Starcounter.XSON.DefaultPatchHandler.Handle(Json root, JsonPatchOperation patchOp, JsonPointer pointer, String value) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9794\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\DefaultPatchHandler.cs:line 38
>    at Starcounter.XSON.JsonPatch.HandleOnePatch(Json root, JsonPatchOperation op, JsonPointer ptr, String value, Int32 patchCount, ChangeLog changeLog, Object sourceJson, Boolean strictRejection, JsonPatchStatus previousStatus) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9794\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 601
>    at Starcounter.XSON.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9794\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 495
>    at Starcounter.XSON.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9794\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 414
>    at Starcounter.Internal.PuppetRestHandler.<>c.<RegisterJsonPatchHandlers>b__7_0(Session session, Request request) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9794\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 130
>    at lambda_method(Closure , Request , IntPtr , IntPtr )
>    at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9794\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 201
>    at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9794\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 96
>    at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\TeamCity10\buildAgent\work\sc-9794\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 348
> ParamName=obj
> HResult=-2147467261

##### Starcounter version 
2.3.1.7529

##### Other information
Can't be reproduce with Content app + Sign In. Website app has to be running.

**Comment by Mihaiii** [comment]
Archiving as it applies to version 1, which is not used by anyone.
Please use version 2, which is much better. :)

Please reopen if it's still reproducible.
